const responseObj = {
  "hey": "Hey! What's up?",
  "how are you": "I am good, thanks for asking!",
  "what's your name?": "I am a friendly chatbot here to help you!",
  "tell me a joke": "Why don't scientists trust atoms? Because they make up everything!",
  "what is the weather like?": "I'm not sure, but you can check your local weather report.",
  "what can you do?": "I can chat with you, tell jokes, provide information, and much more!",
  "who created you?": "I was created by a team of developers to assist you.",
  "what is the capital of India?": "The capital of India is New Delhi.",
  "bye": "Goodbye! Have a great day!",
  "thank you": "You're welcome! If you have any more questions, feel free to ask.",
  "what is your favorite color?": "As a chatbot, I don't have a favorite color, but I think all colors are beautiful!",
  "how old are you?": "I don't have an age, but I'm here to assist you anytime!",
  "what is the meaning of life?": "The meaning of life is a deeply philosophical question. What do you think it is?",
  "can you help me with my homework?": "Sure! I can try to help. What subject are you working on?",
  "what is your favorite movie?": "I don't watch movies, but I've heard that 'The Matrix' is a great one!",
  "do you like music?": "I don't listen to music, but I'd love to hear about your favorite songs!",
  "what is your purpose?": "My purpose is to assist you with any questions or tasks you might have.",
  "where are you from?": "I exist in the digital world, created by developers.",
  "do you have any pets?": "I don't have pets, but I think animals are wonderful!",
  "can you dance?": "I can't dance, but I can certainly chat with you about dancing!",
  "what is artificial intelligence?": "Artificial Intelligence is the simulation of human intelligence in machines that are programmed to think and learn.",
  "tell me a fun fact": "Did you know that honey never spoils? Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible!",
  "what is the time?": "I don't have access to real-time data, but you can check the current time on your device.",
  "can you speak other languages?": "I can understand and respond in multiple languages. Try asking me something in another language!",
  "what is your favorite food?": "I don't eat food, but I can tell you about many delicious dishes!",
  "how do you work?": "I work by processing your input and matching it with pre-defined responses in my database.",
  "can you tell me a story?": "Once upon a time, in a land far, far away, there was a magical chatbot that loved to help people...",
  "how to start coding": "First you have to choose at least a language, which is like a c, c++, java, python etc.",
  "which language should we prefer": "According to your choice, but python is not preferable for DSA, but you can choose this as your first language.",
  "what is dsa" : "DSA stands for Data Structures and Algorithms. It is a fundamental concept in computer science that deals with the study of data structures and algorithms used to organize and manipulate data effectively.Data Structures are ways to store and organize data in a computer so that it can be used efficiently. Examples of data structures include arrays, linked lists, stacks, queues, trees, and graphs.Algorithms are step-by-step procedures or formulas for solving problems. Algorithms define the logic behind how data is manipulated, and they are essential for writing efficient computer programs.In essence, DSA is crucial because it provides a systematic way to understand and solve complex problems efficiently, which is essential in various fields of computer science, such as software development, artificial intelligence, and data analysis.",
  "what is computer" : "A computer is a programmable machine that can process and store data. It can perform tasks according to instructions given to it in the form of programs.Computers consist of hardware and software components. The hardware includes physical components such as the central processing unit (CPU), memory (RAM), storage devices (hard drive, SSD), input devices (keyboard, mouse), and output devices (monitor, printer).",
  "what is c language":"C is a high-level programming language originally developed by Dennis Ritchie at Bell Labs in the early 1970s. It is a general-purpose language known for its efficiency, flexibility, and portability across different platforms.Key Features of C Language:Procedural: C is a procedural language, which means it follows a top-down approach in program design, focusing on functions or procedures that perform specific tasks.Structured: C supports structured programming, allowing for the use of functions, loops, and conditional statements to organize and control the flow of the program.Mid-level: C combines low-level features, such as direct memory manipulation, with high-level constructs, making it suitable for both system programming and application development.Efficient: C is known for its efficiency and is often used for programming where performance and speed are critical, such as in embedded systems and operating systems.Portable: C programs can be compiled to run on different platforms with minimal changes, making it a portable language.",
  "how to start to learn c": "To start learning C, you can follow these steps:Understand the Basics: Familiarize yourself with the basic concepts of programming, such as variables, data types, operators, control structures (like loops and conditional statements), functions, and arrays.Set Up Your Environment: Install a C compiler and an integrated development environment (IDE) on your computer. Popular choices include GCC (GNU Compiler Collection) for Windows, Linux, and macOS, and IDEs like Code::Blocks, Dev-C++, or Visual Studio.Learn the Syntax: Study the syntax of the C language, including how to declare variables, define functions, and use control structures.",
  "which platform is best for c ":"Code::Blocks: Code::Blocks is a free, open-source, and cross-platform IDE that supports C, C++, and Fortran. It is simple to use and provides features like syntax highlighting, code completion, and debugging.Dev-C++: Dev-C++ is a free, open-source IDE for Windows that supports C and C++. It is lightweight and easy to use, making it ideal for beginners.Visual Studio Community: Visual Studio Community is a free, fully-featured IDE from Microsoft that supports various programming languages, including C and C++. It provides a rich set of tools and features, making it suitable for both beginners and experienced developers.Online Platforms: Online platforms like Repl.it, IDEone, and JDoodle allow you to write and compile C code directly in your web browser. They are convenient for quick experiments and learning on the go.Command Line: Using a simple text editor (like Notepad++ on Windows or Nano on Linux) along with a compiler (like GCC) on the command line is a straightforward way to learn C. This method allows you to focus solely on writing and compiling code without any distractions from an IDE.", 
  "today": new Date().toDateString(),
  "time": new Date().toLocaleTimeString(),
};